version: '3.4'

services:
  mqttuya:
    image: mqttuya
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    environment:
      - BROKER
      - PORT
      - USERNAME
      - PASSWORD
      - CLIENTID
      - SUB_TOPICS_LIST